import Head from 'next/head'
import Heroimg from 'public/hero-image.png'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import HowItWorks from './components/HowItWorks'
import Cleaners from './components/Cleaners'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Hero from './components/hero'
import NavbarLayout from './components/NavbarLayout'
import Jiff from './components/Jiff'
import EnderSection from './components/EnderSection'
const inter = Inter({ subsets: ['latin'] })
import { Merriweather} from 'next/font/google'
import {Bodoni} from 'next/font/google'

export default function Home() {
  return (
    <>
    <Head>
        <title>GlaxiClean</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="logo" href="/logo.svg" />
      </Head>
      <main>
          
    <NavbarLayout/>
<Hero/>
<Jiff/>

<Cleaners/>
    <HowItWorks/>
    <EnderSection/>

      </main>
    </>
  )
}
